import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WelcomeDottedBackground from "@/components/bg/welcomedottedcomponent";
import StoreProvider from "@/lib/storeProvide";
import AuthProvider from "@/components/provider/authProvider";
import { Toaster } from "sonner";
import AppleNavbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="relative min-h-screen w-full bg-white ">
        <WelcomeDottedBackground />
        <div className="relative z-10">
          <StoreProvider>
            <AuthProvider>
              <AppleNavbar />
              {children}
              <Toaster position="top-right" richColors />
            </AuthProvider>
          </StoreProvider>
        </div>
      </body>
    </html>
  );
}
